import { useCallback, useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
type Booking = { id:string; customer_name:string; customer_email:string|null; package_name:string; travel_date:string|null; guests:number; total_amount:number; status:string; notes:string|null; };
type Payment = { id:string; booking_id:string; amount:number; method:string; reference:string; received_at:string; };
const db = supabase as any; // Tables become typed after the Karembo schema migration and type generation.
const money = (n:number) => new Intl.NumberFormat("en-KE",{style:"currency",currency:"KES"}).format(n);
export default function Bookings() {
 const [rows,setRows]=useState<Booking[]>([]);
 const [payments,setPayments]=useState<Payment[]>([]);
 const [selected,setSelected]=useState("");
 const [busy,setBusy]=useState(false);
 const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [pkg,setPkg]=useState(""); const [amount,setAmount]=useState(""); const [date,setDate]=useState(""); const [guests,setGuests]=useState("1");
 const [paid,setPaid]=useState(""); const [method,setMethod]=useState("mpesa"); const [reference,setReference]=useState("");
 const load=useCallback(async()=>{
  const [b,p]=await Promise.all([db.from("manual_bookings").select("*").order("created_at",{ascending:false}),db.from("manual_payment_records").select("*").order("received_at",{ascending:false})]);
  if(b.error || p.error){toast.error("Manual booking tables are not ready or admin access is denied. Apply the reviewed Karembo migration first.");return;}
  setRows(b.data||[]);setPayments(p.data||[]);
 },[]);
 useEffect(()=>{void load();},[load]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();const total=Number(amount);const count=Number(guests);if(!name.trim()||!pkg.trim()||!Number.isFinite(total)||total<0||!Number.isInteger(count)||count<1)return toast.error("Enter valid booking details.");setBusy(true);const {error}=await db.from("manual_bookings").insert({customer_name:name.trim(),customer_email:email.trim()||null,package_name:pkg.trim(),travel_date:date||null,guests:count,total_amount:total,status:"awaiting_payment"});setBusy(false);if(error)return toast.error(error.message);toast.success("Booking created");setName("");setEmail("");setPkg("");setAmount("");setDate("");void load();};
 const record=async(e:React.FormEvent)=>{e.preventDefault();const booking=rows.find(r=>r.id===selected);const value=Number(paid);const already=payments.filter(p=>p.booking_id===selected).reduce((a,p)=>a+Number(p.amount),0);if(!booking||booking.status==="cancelled"||!reference.trim()||!Number.isFinite(value)||value<=0||value>Number(booking.total_amount)-already)return toast.error("Check payment details and outstanding balance.");const {data:{user}}=await supabase.auth.getUser();if(!user)return toast.error("Sign in again.");setBusy(true);const {error}=await db.from("manual_payment_records").insert({booking_id:selected,amount:value,method,reference:reference.trim(),recorded_by:user.id});if(error){setBusy(false);return toast.error(error.message);}const next=already+value>=Number(booking.total_amount)?"paid":"partially_paid";const result=await db.from("manual_bookings").update({status:next}).eq("id",selected);setBusy(false);if(result.error)toast.error("Payment recorded but booking status needs attention: "+result.error.message);else toast.success("Manual payment recorded");setPaid("");setReference("");void load();};
 const changeStatus=async(booking:Booking,status:string)=>{if(status==="paid"||status==="partially_paid")return toast.error("Payment statuses are determined from recorded payments.");const balance=Number(booking.total_amount)-payments.filter(p=>p.booking_id===booking.id).reduce((a,p)=>a+Number(p.amount),0);if(status==="confirmed"&&balance>0&&!window.confirm("This booking has an outstanding balance. Confirm anyway?"))return;const {error}=await db.from("manual_bookings").update({status}).eq("id",booking.id);if(error)return toast.error(error.message);toast.success("Booking status updated");void load();};
 return <div className="space-y-6"><div><h1 className="text-3xl font-bold">Bookings & manual payments</h1><p className="text-sm text-slate-600 mt-1">Record bookings and payments received outside the website. No online charging.</p></div>
 <form onSubmit={create} className="bg-white rounded-xl p-5 shadow-sm space-y-3"><h2 className="font-bold text-lg">New booking</h2><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{[[name,setName,"Customer name"],[email,setEmail,"Email"],[pkg,setPkg,"Tour package"],[amount,setAmount,"Total amount (KES)"],[guests,setGuests,"Guests"]].map(([v,set,label])=><label key={label as string} className="text-sm">{label as string}<input required={label==="Customer name"||label==="Tour package"||label==="Total amount (KES)"||label==="Guests"} type={label==="Email"?"email":label==="Guests"||label==="Total amount (KES)"?"number":"text"} min={label==="Guests"?"1":"0"} step={label==="Total amount (KES)"?"0.01":"1"} value={v as string} onChange={e=>(set as (value:string)=>void)(e.target.value)} className="mt-1 block w-full rounded-md border p-2" /></label>)}<label className="text-sm">Travel date<input type="date" value={date} onChange={e=>setDate(e.target.value)} className="mt-1 block w-full rounded-md border p-2"/></label></div><Button disabled={busy}>Create booking</Button></form>
 <section className="bg-white rounded-xl shadow-sm p-5"><h2 className="font-bold text-lg mb-4">Booking register</h2><div className="overflow-x-auto"><table className="w-full text-sm text-left"><thead><tr className="border-b">{["Customer / tour","Travel date","Total","Received","Balance","Status"].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{rows.map(b=>{const received=payments.filter(p=>p.booking_id===b.id).reduce((a,p)=>a+Number(p.amount),0);return <tr key={b.id} className="border-b"><td className="p-2"><strong>{b.customer_name}</strong><div className="text-slate-500">{b.package_name}</div></td><td className="p-2">{b.travel_date||"TBD"}</td><td className="p-2">{money(Number(b.total_amount))}</td><td className="p-2">{money(received)}</td><td className="p-2">{money(Number(b.total_amount)-received)}</td><td className="p-2"><select aria-label={`Status for ${b.customer_name}`} value={b.status} disabled={busy} onChange={e=>void changeStatus(b,e.target.value)} className="rounded border p-2">{["pending","awaiting_payment","partially_paid","paid","confirmed","cancelled"].map(s=><option key={s} value={s} disabled={s==="paid"||s==="partially_paid"}>{s.replaceAll("_"," ")}</option>)}</select></td></tr>})}</tbody></table>{rows.length===0&&<p className="text-sm text-slate-500 py-4">No bookings recorded yet.</p>}</div></section>
 <form onSubmit={record} className="bg-white rounded-xl p-5 shadow-sm space-y-3"><h2 className="font-bold text-lg">Record received payment</h2><div className="grid sm:grid-cols-2 gap-3"><label className="text-sm">Booking<select required value={selected} onChange={e=>setSelected(e.target.value)} className="block w-full mt-1 rounded border p-2"><option value="">Choose booking</option>{rows.filter(b=>b.status!=="cancelled"&&payments.filter(p=>p.booking_id===b.id).reduce((a,p)=>a+Number(p.amount),0)<Number(b.total_amount)).map(b=><option key={b.id} value={b.id}>{b.customer_name} — {b.package_name}</option>)}</select></label><label className="text-sm">Amount received (KES)<input required type="number" min=".01" step=".01" value={paid} onChange={e=>setPaid(e.target.value)} className="block w-full mt-1 rounded border p-2"/></label><label className="text-sm">Method<select value={method} onChange={e=>setMethod(e.target.value)} className="block w-full mt-1 rounded border p-2"><option value="mpesa">M-Pesa</option><option value="bank_transfer">Bank transfer</option><option value="cash">Cash</option><option value="other">Other</option></select></label><label className="text-sm">Transaction reference<input required value={reference} onChange={e=>setReference(e.target.value)} className="block w-full mt-1 rounded border p-2"/></label></div><Button disabled={busy||!selected}>Record payment</Button><p className="text-xs text-slate-500">Verify the payment externally before recording it. Entries cannot be edited or deleted.</p></form></div>;
}
